### ISSUE TITLE
[1.12.2] Leaves not registered by other mods.

### ISSUE THREAD

**Issue by KathySharks** [Liahim85/MistyWorld_Open#17]
While using BetterFoliage and PassableLeaves, most modded/vanilla leaves are affected by these two mods.
However leaves implemented by MistyWorld are not recognized by either. 
It seems that the issue comes specifically from how this mod registers its leaf blocks since PassableLeaves simply looks for generic leaf blocks under the hood and gives them said properties. 

Alternatively, leaf blocks from MistyWorld could be made passable with the use of a config option. But that would be an odd redundancy.

PS : The Mist at lower altitudes is a genius concept. Stoked to see what you'll add next.

**Comment by Liahim85** [comment]
Thanks for the tip ...
The fact is that I do not use vanilla foliage as a parent.
Foliage from the Misty World is a completely new development and it has nothing to do with vanilla. This is due to the parameters laid down in the principle of tree growth.

Maybe in the future, I'll try to link the Misty World more closely with other mods, but not now. Now the main goal is to finish the development of the world.

P.S. If necessary, I can add foliage permeability in the settings.
