### ISSUE TITLE
Recipe conflict

### ISSUE THREAD

**Issue by rilllan** [Liahim85/MistyWorld_Open#26]
Quark adds chests for each of the different types of wood, and for some reason when this and quark are installed this mod overrides the recipe and just gives me the default chest.

**Comment by Liahim85** [comment]
I think that this is due to the load order of mods.
And in general, the forge has not yet worked out a priority system for recipes.
As a solution option: you can edit the recipe of the chest yourself.
Open the file: `assets/mist/resipes/chest.json` and replace the line `"#TREE_STEPS_AND_ORE_PLANKS"` with `"#TREE_STEPS"`.
