### ISSUE TITLE
JEI Recipe Spam

### ISSUE THREAD

**Issue by ghost** [Liahim85/MistyWorld_Open#33]
Minecraft Version: 1.12.2
Forge Build: 2611
JEI Version: 4.8.5.151 (and 4.8.5.147)
Mod Version: alpha b 04_

Many recipes in JEI are duplicated, which is especially noticeable with wood planks. Some of these recipes are the regular minecraft ones, but there are quite a few that JEI attributes to Misty World. I assume this is due to the mod adding recipes for wooden items out of the various wooden planks the mod adds. Shouldn't these items be made valid ingredients for the relevant recipes if they're simply added to the correct oredict entries, thus removing the necessity of adding new recipes to achieve the same effect?

**Comment by Liahim85** [comment]
Yes you are right.
These recipes were added when the forge did not yet have an adequate system for working with the oredict. That was the time of transition to .json-recipe system.
Since then, I have not checked if the oredict is working fine... I guess I'll do that a little later. Thanks for the suggestion.
