### ISSUE TITLE
[Question] What determines the Pollution Rate of Filter Coal?

### ISSUE THREAD

**Issue by davqvist** [Liahim85/MistyWorld_Open#43]
Hi, this is not an issue, just a question.
I have gotten several reports of people complaining that the Filter Coal in the Respirator gets depleted too fast (only lasting like 30 seconds) while I have never encountered that myself and also seen videos of other being in the mist for easily over 10 minutes. 

Obviously there are factors that change how long the Filter Coal lasts. Can you explain what that is?

**Comment by Liahim85** [comment]
Yes, I also noticed this in some videos.
The fact is that there are certain areas (I call them centers) in which fog is much more toxic than in other places.
These areas are generated in certain coordinates (indicated by the Mysterious disk, by the way). Relative to these coordinates, the level of fog toxicity is also determined. However, these areas should never be near the borders of the "islands".
I assume that this mechanism does not work correctly, but I can not find the reason yet...
Perhaps this is due to the discrepancy between the generated world and the current seed.

**Comment by Liahim85** [comment]
@davqvist, can I ask you to send me a folder with the world in which this error is observed?

**Comment by davqvist** [comment]
Sorry I missed your question. I don't really have access to one of the players that have that issue. I can ask if they can provide it.

**Comment by Liahim85** [comment]
Hi @davqvist! I tried to change the mechanism of getting the damage from the fog. Can you update my mod and check if it works?

**Comment by davqvist** [comment]
I did some tests and haven't found any issues, updated the pack, let's hope everything is fine.

**Comment by Liahim85** [comment]
O! Thank you) I hope that's the way it is )
