### ISSUE TITLE
Config option for can't sleep if friend is in misty world

### ISSUE THREAD

**Issue by ewanm89** [Liahim85/MistyWorld_Open#86]
When running a public server for lots of players, it would be good to be able to disable the sleep dimension locking thing as it is not really sensible to get upto 15 players to all be in the overworld. It is an interesting feature, and would work well in small coop groups but not so much on anything much larger than that.

Either that, or a way to read ftbutils teams or similar for the "friends" to trigger on.

**Comment by Liahim85** [comment]
This feature is not just an interesting idea, it is a technical necessity. Otherwise, it would be impossible to let players sleep in the Misty World.
In addition, in order to fall asleep, it is not necessary for all players to return to the overworld. Just go to bed at the same time. Just like in the overworld.

**Comment by ewanm89** [comment]
That is not correct when most modded servers use something like Morpheus or Quark to require only a percentage of players to sleep at any one time. This hijacking of the checks does break that.

It also breaks comforts which allows one to use a hammock to sleep the day away to make it night.

Finally, no, there is no technical reason why sleeping in the Misty World should require it to be all players, same in the overworld to allow the sleep to happen. There are several mods which add dimensions that handle sleep just fine with Morpheus or Quark.
